### ISSUE TITLE
Quickstart Guide doesnt work for me

### ISSUE THREAD

**Issue by Dutzel** [openskies-sh/flight-blender#30]
Hello Openskies-Team,

i just cloned your repo and followed your quickstart guide step by step, but it didnt work as expected. Here is my log:

Hope this helps :)

**Comment by hrishiballal** [comment]
Hello @Dutzel , thank you for this, it looks like this is a issue with your Postgres, can you confirm you have a .env file that has the [username / password](https://github.com/openskies-sh/flight-blender/blob/master/deployment_support/.env.local#L39) etc? 

In my experience, it helps if you prune the system in case there is older volume / existing Postgres.
