### ISSUE TITLE
openapi schema does not reflect paginated results

### ISSUE THREAD

**Issue by vgrafe** [openskies-sh/flight-blender#59]
This was observed with the `flight_declaration_ops/flight_declaration` (response described [here](https://github.com/openskies-sh/flight-blender/blob/15b4154cb54b23e53eb372d253e24abbb10bfa3d/api/flight-blender-1.0.0-resolved.yaml#L1093)) endpoint for now, but it's probably worth checking if other endpoints are not properly described.

The actual response is a pagination payload, with properties such as page count current page results, etc I assume is generated by Django.

This is not critical but breaks developer workflows such as typegen based on openapi schema, which is how I found this disparity.

**Comment by hrishiballal** [comment]
Thank you for this, I will look into this, the pagination is a Django setting from Django rest framework, let me take a look and update this.
